enum ActionTypes{
  RECEIVE_TWEETS = 'RECEIVE_TWEETS',
  RECEIVE_USERS = 'RECEIVE_USERS',
  SET_AUTH_USER = 'SET_AUTH_USER',
  TOGGLE_TWEET = 'TOGGLE_TWEET',
  ADD_TWEET = 'ADD_TWEET',
}

export default ActionTypes